### ISSUE TITLE
Hugging face api code causes an error

### ISSUE THREAD

**Issue by Hobospider132** [Hobospider132/MahiruShiinaJS#4]
`TypeError: huggingface.query is not a function
    at Object.execute (/home/runner/MahiruShiinaJS/commands/mahiru.js:16:34)
    at Client.<anonymous> (/home/runner/MahiruShiinaJS/index.js:55:17)
    at Client.emit (node:events:513:28)
    at Client.emit (node:domain:489:12)
    at InteractionCreateAction.handle (/home/runner/MahiruShiinaJS/node_modules/discord.js/src/client/actions/InteractionCreate.js:97:12)
    at module.exports [as INTERACTION_CREATE] (/home/runner/MahiruShiinaJS/node_modules/discord.js/src/client/websocket/handlers/INTERACTION_CREATE.js:4:36)
    at WebSocketManager.handlePacket (/home/runner/MahiruShiinaJS/node_modules/discord.js/src/client/websocket/WebSocketManager.js:352:31)
    at WebSocketShard.onPacket (/home/runner/MahiruShiinaJS/node_modules/discord.js/src/client/websocket/WebSocketShard.js:489:22)
    at WebSocketShard.onMessage (/home/runner/MahiruShiinaJS/node_modules/discord.js/src/client/websocket/WebSocketShard.js:328:10)
TypeError: huggingface.query is not a function
    at Object.execute (/home/runner/MahiruShiinaJS/commands/mahiru.js:16:34)
    at Client.<anonymous> (/home/runner/MahiruShiinaJS/index.js:55:17)
    at Client.emit (node:events:513:28)
    at Client.emit (node:domain:489:12)
    at InteractionCreateAction.handle (/home/runner/MahiruShiinaJS/node_modules/discord.js/src/client/actions/InteractionCreate.js:97:12)
    at module.exports [as INTERACTION_CREATE] (/home/runner/MahiruShiinaJS/node_modules/discord.js/src/client/websocket/handlers/INTERACTION_CREATE.js:4:36)
    at WebSocketManager.handlePacket (/home/runner/MahiruShiinaJS/node_modules/discord.js/src/client/websocket/WebSocketManager.js:352:31)
    at WebSocketShard.onPacket (/home/runner/MahiruShiinaJS/node_modules/discord.js/src/client/websocket/WebSocketShard.js:489:22)
    at WebSocketShard.onMessage (/home/runner/MahiruShiinaJS/node_modules/discord.js/src/client/websocket/WebSocketShard.js:328:10)`

need to look into new way of calling it

**Comment by Hobospider132** [comment]
solution: call as query not as huggingface.query
